### ISSUE TITLE
Use of ssh configured remote breaks pipelines

### ISSUE THREAD

**Issue by gondoi** [pivotal-cf/cf-rabbitmq-smoke-tests#3]
We are using this smoke tests in a pipeline as a resource and the usage of git via ssh has broken the test. Since these repos were originally all public, we did not need an SSH key to pull them down. Now that a new submodule that uses SSH has been added, the git submodule update fails because there is no key in the container being used in concourse. Can we get this changed to `https` since it is public as well?

https://github.com/pivotal-cf/cf-rabbitmq-smoke-tests/blob/master/.gitmodules#L24

**Comment by albertoleal** [comment]
Hey @gondoi, thanks for your PR. It's been merged now :)
